events{
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    server {
        listen 80;
        server_name library.test;
        root /srv/nginx-handbook-projects/static-demo;
    }


    server {
        listen 8080;
        server_name librarian.library.test;

        return 200 "hello, its from sujXX.test\n";
    }
}
