events {
}

http {
    include      /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Server 1
    server {
        listen      80;
        server_name library.test;
        root        /srv/nginx-handbook-projects/static-demo;
    }

    # Server 2
    server {
        listen      8080;
        server_name librarian.library.test;

        location /agatha {
            return 200 "Miss Marple.\nHercule Poirot.\n";
        }
    }

    # Server 3
    server {
        listen      8000;
        server_name nginx-handbook.test;
        root        /srv/nginx-handbook-projects/static-demo;

        location  /index_page {
            return 307 /index.html;
        }

        location = /about_page {
            return 307 /about.html;
        }
    }
}
