events{
}
http {
    server {
        listen 80;
        server_name library.test;

        return 200 "hello, its from sujX.test \n";
    }


    server {
        listen 80;
        server_name librarian.library.test;

        return 200 "hello, its from sujXX.test\n";
    }
}
